function trial_option_screen(main_window)

% Gait Initiation Message
dim1 = [0.125,0.70,0.75,0.1];
str1 = 'Gait Initiation';
annotation('textbox',dim1,'String',str1,...
    'FontName','Arial','FontSize',108,...
    'EdgeColor','none',...
    'HorizontalAlignment','center','VerticalAlignment','middle');

% Selection Message
dim1 = [0.125,0.55,0.75,0.1];
str1 = 'Select Trial Type:';
annotation('textbox',dim1,'String',str1,...
    'FontName','Arial','FontSize',52,...
    'EdgeColor','none',...
    'HorizontalAlignment','center','VerticalAlignment','middle');


% Check if buttons already exist
if isfield(main_window.UserData,'trial_buttons')
    set(main_window.UserData.trial_buttons,'Visible','On');
else
    % Cued
    cued_button = uicontrol('Parent',main_window,...
        'Style','pushbutton',...
        'BackgroundColor','white',...
        'String','Cued',...
        'FontSize',36,...
        'Units','normalized',...
        'Position',[0.40 0.50 0.20 0.06],...
        'Tag','Cued_Trial_button',...
        'Callback',@run_trial);
    
    % Self Initiated
    si_button = uicontrol('Parent',main_window,...
        'Style','pushbutton',...
        'BackgroundColor','white',...
        'String','Self-Initiated',...
        'FontSize',36,...
        'Units','normalized',...
        'Position',[0.40 0.40 0.20 0.06],...
        'Tag','SI_Trial_button',...
        'Callback',@run_trial);
    
    % Prepare-and-go
    pag_button = uicontrol('Parent',main_window,...
        'Style','pushbutton',...
        'BackgroundColor','white',...
        'String','Prepare-and-Go',...
        'FontSize',36,...
        'Units','normalized',...
        'Position',[0.40 0.30 0.20 0.06],...
        'Tag','PAG_Trial_button',...
        'Callback',@run_trial);
    
    % Store trial buttons in user data
    main_window.UserData.trial_buttons = [cued_button,si_button,pag_button];
    
    % Create auto save file
    fid = fopen([main_window.UserData.subid,'_GI_',datestr(now,'yy-mm-dd_HH-MM-SS'),'.asd'],'w');
    main_window.UserData.auto_save_file = fid;
end
end