function createDataSourcePanel(main_window)
%% Create main panel
data_panel = uipanel('Title','Data sources','FontSize',26,...
             'BackgroundColor','white',...
             'BorderType','none',...
             'Units','normalized',...
             'Position',[0.01 0.5 0.2 0.49]);

%% Add text and buttons
% Left INS
left_INS_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.935 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Left INS',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.93 0.45 0.06]);

 uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.93 0.4 0.06],...
    'Tag','Left_INS_button',...
    'Callback',@loadData);

% Left LFP indicator
left_lfp_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','LFP',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.12,0.86,0.38,0.06]);

% Left Accelerometry indicator
left_accel_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Accelerometry',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.58,0.86,0.38,0.06]);

% Left Settings indicator
left_settings_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Settings',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.12,0.79,0.38,0.06]);

% Left Log indicator
left_logs_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Logs',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.58,0.79,0.38,0.06]);

% Right INS
right_INS_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.725 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Right INS',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.72 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.72 0.4 0.06],...
    'Tag','Right_INS_button',...
    'Callback',@loadData);

% Right LFP indicator
right_lfp_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','LFP',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.12,0.6550,0.38,0.06]);

% Left Accelerometry indicator
right_accel_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Accelerometry',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.58,0.6550,0.38,0.06]);

% Left Settings indicator
right_settings_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Settings',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.12,0.585,0.38,0.06]);

% Left Log indicator
right_logs_indicator = uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Logs',...
    'FontSize',14,...,
    'HorizontalAlignment','center',...
    'BackgroundColor',[192,192,192]./256,...
    'Units','normalized',...
    'Position',[0.58,0.585,0.38,0.06]);

% Delsys
delsys_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.515 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Delsys',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.51 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.51 0.4 0.06],...
    'Tag','Delsys_button',...
    'Callback',@loadData);

% Xsens
xsens_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.445 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Xsens',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.44 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.44 0.4 0.06],...
    'Tag','Xsens_button',...
    'Callback',@loadData);

% Vicon force plate (specific for gait initation)
force_plate_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.375 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Force Plate',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.37 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.37 0.4 0.06],...
    'Tag','Force_plate_button',...
    'Callback',@loadData);

% Rover Left
left_rover_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.305 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Left Rover',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.30 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.30 0.4 0.06],...
    'Tag','Left_rover_button',...
    'Callback',@loadData);

% Rover Right
right_rover_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.235 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Right Rover',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.23 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.23 0.4 0.06],...
    'Tag','Right_rover_button',...
    'Callback',@loadData);

% Trial number
uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Trial Number',...
    'FontSize',16,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.02 0.075 0.30 0.06]);

uicontrol('Parent',data_panel,...
    'Style','edit',...
    'BackgroundColor','white',...
    'String','N/A',...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[0.33 0.070 0.24 0.06],...
    'Tag','trial_num_edit',...
    'Callback',@changeTrialNum);

% Stim Condition
uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Stim Cond',...
    'FontSize',16,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.02 0.005 0.23 0.06]);

uicontrol('Parent',data_panel,...
    'Style','popupmenu',...
    'BackgroundColor','white',...
    'String',{'OFF','ON','aDBS'},...
    'Value',1,...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[0.26 0.005 0.24 0.06],...
    'Tag','Stim_condition_drop_down',...
    'Callback',@changeStimMedCondition);

% Med Condition
uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Med Cond',...
    'FontSize',16,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.51 0.005 0.23 0.06]);

uicontrol('Parent',data_panel,...
    'Style','popupmenu',...
    'BackgroundColor','white',...
    'String',{'ON','OFF'},...
    'Value',1,...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[0.75 0.005 0.24 0.06],...
    'Tag','Med_condition_drop_down',...
    'Callback',@changeStimMedCondition);

% Set user data to change colors when things are loaded
main_window.UserData.indicators.left_INS = left_INS_indicator;
main_window.UserData.indicators.left_LFP = left_lfp_indicator;
main_window.UserData.indicators.left_accel = left_accel_indicator;
main_window.UserData.indicators.left_settings = left_settings_indicator;
main_window.UserData.indicators.left_logs = left_logs_indicator;
main_window.UserData.indicators.right_INS = right_INS_indicator;
main_window.UserData.indicators.right_LFP = right_lfp_indicator;
main_window.UserData.indicators.right_accel = right_accel_indicator;
main_window.UserData.indicators.right_settings = right_settings_indicator;
main_window.UserData.indicators.right_logs = right_logs_indicator;
main_window.UserData.indicators.delsys = delsys_indicator;
main_window.UserData.indicators.xsens = xsens_indicator;
main_window.UserData.indicators.fp = force_plate_indicator;
main_window.UserData.indicators.left_rover = left_rover_indicator;
main_window.UserData.indicators.right_rover = right_rover_indicator;


end