function createPlotOptionPanel(main_window)
%% Plot options
plot_options_panel = uipanel('Title','Plot options:',...
    'FontSize',18,...
    'BackgroundColor','white',...
    'BorderType','none',...
    'Units','normalized',...
    'Position',[0.89 0.2 0.1 0.79]);

% Plot window 1
window1_bg = uibuttongroup('Parent',plot_options_panel,...
    'Title','Plot window 1:',...
    'FontSize',16,...
    'BackgroundColor','white',...
    'BorderType','none',...
    'Units','normalized',...
    'Position',[0.01 0.815 0.98,0.16]);
uicontrol('Parent',window1_bg,...
    'Style','text',...
    'String','Source:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.75,0.98,0.24]);
w(1,1) = uicontrol('Parent',window1_bg,...
    'Callback',@updatePlotSelectionOptions,...
    'Style','popupmenu',...
    'String',' ',...
    'BackgroundColor','white',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.01,0.5,0.98,0.24],...
    'Enable','inactive');
uicontrol('Parent',window1_bg,...
    'Style','text',...
    'String','Sub-variable:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.265,0.98,0.24]);
w(1,2) = uicontrol('Parent',window1_bg,...
    'Callback',@plotData,...
    'Style','popupmenu',...
    'String',' ',...
    'Fontsize',12,...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.01,0.01,0.98,0.24],...
    'Enable','inactive');

% Plot window 2
window2_bg = uibuttongroup('Parent',plot_options_panel,...
    'Title','Plot window 2:',...
    'FontSize',16,...
    'BackgroundColor','white',...
    'BorderType','none',...
    'Units','normalized',...
    'Position',[0.01 0.645 0.98,0.16]);
uicontrol('Parent',window2_bg,...
    'Style','text',...
    'String','Source:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.75,0.98,0.24]);
w(2,1) = uicontrol('Parent',window2_bg,...
    'Callback',@updatePlotSelectionOptions,...
    'Style','popupmenu',...
    'String',' ',...
    'BackgroundColor','white',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.01,0.5,0.98,0.24],...
    'Enable','inactive');
uicontrol('Parent',window2_bg,...
    'Style','text',...
    'String','Sub-variable:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.265,0.98,0.24]);
w(2,2) = uicontrol('Parent',window2_bg,...
    'Callback',@plotData,...
    'Style','popupmenu',...
    'String',' ',...
    'Fontsize',12,...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.01,0.01,0.98,0.24],...
    'Enable','inactive');

% Plot data type
window3_bg = uibuttongroup('Parent',plot_options_panel,...
    'Title','Plot window 3:',...
    'FontSize',16,...
    'BackgroundColor','white',...
    'BorderType','none',...
    'Units','normalized',...
    'Position',[0.01 0.475 0.98,0.16]);
uicontrol('Parent',window3_bg,...
    'Style','text',...
    'String','Source:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.75,0.98,0.24]);
w(3,1) = uicontrol('Parent',window3_bg,...
    'Callback',@updatePlotSelectionOptions,...
    'Style','popupmenu',...
    'String',' ',...
    'BackgroundColor','white',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.01,0.5,0.98,0.24],...
    'Enable','inactive');
uicontrol('Parent',window3_bg,...
    'Style','text',...
    'String','Sub-variable:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.265,0.98,0.24]);
w(3,2) = uicontrol('Parent',window3_bg,...
    'Callback',@plotData,...
    'Style','popupmenu',...
    'String',' ',...
    'Fontsize',12,...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.01,0.01,0.98,0.24],...
    'Enable','inactive');

% Plot data type
window4_bg = uibuttongroup('Parent',plot_options_panel,...
    'Title','Plot window 4:',...
    'FontSize',16,...
    'BackgroundColor','white',...
    'BorderType','none',...
    'Units','normalized',...
    'Position',[0.01 0.305 0.98,0.16]);
uicontrol('Parent',window4_bg,...
    'Style','text',...
    'String','Source:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.75,0.98,0.24]);
w(4,1) = uicontrol('Parent',window4_bg,...
    'Callback',@updatePlotSelectionOptions,...
    'Style','popupmenu',...
    'String',' ',...
    'BackgroundColor','white',...
    'FontSize',12,...
    'Units','normalized',...
    'Position',[0.01,0.5,0.98,0.24],...
    'Enable','inactive');
uicontrol('Parent',window4_bg,...
    'Style','text',...
    'String','Sub-variable:',...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'FontSize',14,...
    'Units','normalized',...
    'Position',[0.01,0.265,0.98,0.24]);
w(4,2) = uicontrol('Parent',window4_bg,...
    'Callback',@plotData,...
    'Style','popupmenu',...
    'String',' ',...
    'Fontsize',12,...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.01,0.01,0.98,0.24],...
    'Enable','inactive');

% Zoom button
uicontrol('Parent',plot_options_panel,...
    'Style','togglebutton',...
    'BackgroundColor','white',...
    'String','Zoom toggle',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.01 0.20 0.98 0.05],...
    'Tag','Left_LFP_button',...
    'Callback',@setZoom);

% Add plot option struct to user data of figure
main_window.UserData.plot_options.sources = w;
end