function createDataSourcePanel(main_window)
%% Create main panel
data_panel = uipanel('Title','Data sources','FontSize',32,...
             'BackgroundColor','white',...
             'BorderType','none',...
             'Units','normalized',...
             'Position',[0.01 0.6 0.2 0.39]);

%% Add text and buttons
% Left LFP
left_LFP_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.9 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Left LFP',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.895 0.45 0.09]);

 uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.895 0.4 0.09],...
    'Tag','Left_LFP_button',...
    'Callback',@loadData);

% Right LFP
right_LFP_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.80 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Right LFP',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.795 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.795 0.4 0.09],...
    'Tag','Right_LFP_button',...
    'Callback',@loadData);

% Left Accel
left_accel_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.70 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Left Accel',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.695 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.695 0.4 0.09],...
    'Tag','Left_Accel_button',...
    'Callback',@loadData);

% Right Accel
right_accel_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.60 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Right Accel',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.595 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.595 0.4 0.09],...
    'Tag','Right_Accel_button',...
    'Callback',@loadData);

% Left RC+S Device Settings
left_device_settings_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.50 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','L Rec Settings',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.495 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.495 0.4 0.09],...
    'Tag','Left_Device_Settings_button',...
    'Callback',@loadData);

% Right RC+S Device Settings
right_device_settings_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.40 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','R Rec Settings',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.395 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.395 0.4 0.09],...
    'Tag','Right_Device_Settings_button',...
    'Callback',@loadData);

% Delsys
delsys_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.3 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Delsys',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.295 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.295 0.4 0.09],...
    'Tag','Delsys_button',...
    'Callback',@loadData);

% Xsens
xsens_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.2050 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Xsens',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.20 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.20 0.4 0.09],...
    'Tag','Xsens_button',...
    'Callback',@loadData);

% Vicon force plate (specific for gait initation)
force_plate_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.1050 0.07 0.07]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Force Plate',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.10 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.10 0.4 0.09],...
    'Tag','Force_plate_button',...
    'Callback',@loadData);

% Stim Condition
uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Stim Condition',...
    'FontSize',24,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.005 0.45 0.09]);

uicontrol('Parent',data_panel,...
    'Style','popupmenu',...
    'BackgroundColor','white',...
    'String',{'OFF','ON','aDBS'},...
    'Value',1,...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.005 0.4 0.09],...
    'Tag','Stim_condition_drop_down',...
    'Callback',@changeStimCondition);

% Set user data to change colors when things are loaded
main_window.UserData.indicators.left_LFP = left_LFP_indicator;
main_window.UserData.indicators.right_LFP = right_LFP_indicator;
main_window.UserData.indicators.left_accel = left_accel_indicator;
main_window.UserData.indicators.right_accel = right_accel_indicator;
main_window.UserData.indicators.left_device_settings = left_device_settings_indicator;
main_window.UserData.indicators.right_device_settings = right_device_settings_indicator;
main_window.UserData.indicators.delsys = delsys_indicator;
main_window.UserData.indicators.xsens = xsens_indicator;
main_window.UserData.indicators.fp = force_plate_indicator;

end