function createDataSourcePanel(main_window)
%% Create main panel
data_panel = uipanel('Title','Data sources','FontSize',26,...
             'BackgroundColor','white',...
             'BorderType','none',...
             'Units','normalized',...
             'Position',[0.01 0.5 0.2 0.49]);

%% Add text and buttons
% Left LFP
left_LFP_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.935 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Left LFP',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.93 0.45 0.06]);

 uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.93 0.4 0.06],...
    'Tag','Left_LFP_button',...
    'Callback',@loadData);

% Right LFP
right_LFP_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.865 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Right LFP',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.86 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.86 0.4 0.06],...
    'Tag','Right_LFP_button',...
    'Callback',@loadData);

% Left Accel
left_accel_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.795 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Left Accel',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.79 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.79 0.4 0.06],...
    'Tag','Left_Accel_button',...
    'Callback',@loadData);

% Right Accel
right_accel_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.725 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Right Accel',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.72 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.72 0.4 0.06],...
    'Tag','Right_Accel_button',...
    'Callback',@loadData);

% Left RC+S Device Settings
left_device_settings_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.655 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','L Rec Settings',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.65 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.65 0.4 0.06],...
    'Tag','Left_Device_Settings_button',...
    'Callback',@loadData);

% Right RC+S Device Settings
right_device_settings_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.585 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','R Rec Settings',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.58 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.58 0.4 0.06],...
    'Tag','Right_Device_Settings_button',...
    'Callback',@loadData);

% Delsys
delsys_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.515 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Delsys',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.51 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.51 0.4 0.06],...
    'Tag','Delsys_button',...
    'Callback',@loadData);

% Xsens
xsens_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.445 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Xsens',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.44 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.44 0.4 0.06],...
    'Tag','Xsens_button',...
    'Callback',@loadData);

% Vicon force plate (specific for gait initation)
force_plate_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.375 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Force Plate',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.37 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.37 0.4 0.06],...
    'Tag','Force_plate_button',...
    'Callback',@loadData);

% Teensey (specific for Kara)
teensey_indicator = uicontrol('Parent',data_panel,...
    'Style','radiobutton',...
    'BackgroundColor','white',...
    'Value',false,...
    'Enable','inactive',...
    'Units','normalized',...
    'Position',[0.03 0.305 0.05 0.05]);

uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Teensey',...
    'FontSize',20,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.12 0.30 0.45 0.06]);

uicontrol('Parent',data_panel,...
    'Style','pushbutton',...
    'BackgroundColor','white',...
    'String','Load data',...
    'FontSize',20,...
    'Units','normalized',...
    'Position',[0.58 0.30 0.4 0.06],...
    'Tag','Teensey_button',...
    'Callback',@loadData);

% Trial number
uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Trial Number',...
    'FontSize',16,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.02 0.075 0.30 0.06]);

uicontrol('Parent',data_panel,...
    'Style','edit',...
    'BackgroundColor','white',...
    'String','N/A',...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[0.33 0.070 0.24 0.06],...
    'Tag','trial_num_edit',...
    'Callback',@changeTrialNum);

% Stim Condition
uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Stim Cond',...
    'FontSize',16,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.02 0.005 0.23 0.06]);

uicontrol('Parent',data_panel,...
    'Style','popupmenu',...
    'BackgroundColor','white',...
    'String',{'OFF','ON','aDBS'},...
    'Value',1,...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[0.26 0.005 0.24 0.06],...
    'Tag','Stim_condition_drop_down',...
    'Callback',@changeStimMedCondition);

% Med Condition
uicontrol('Parent',data_panel,...
    'Style','text',...
    'String','Med Cond',...
    'FontSize',16,...
    'HorizontalAlignment','left',...
    'BackgroundColor','white',...
    'Units','normalized',...
    'Position',[0.51 0.005 0.23 0.06]);

uicontrol('Parent',data_panel,...
    'Style','popupmenu',...
    'BackgroundColor','white',...
    'String',{'ON','OFF'},...
    'Value',1,...
    'FontSize',16,...
    'Units','normalized',...
    'Position',[0.75 0.005 0.24 0.06],...
    'Tag','Med_condition_drop_down',...
    'Callback',@changeStimMedCondition);

% Set user data to change colors when things are loaded
main_window.UserData.indicators.left_LFP = left_LFP_indicator;
main_window.UserData.indicators.right_LFP = right_LFP_indicator;
main_window.UserData.indicators.left_accel = left_accel_indicator;
main_window.UserData.indicators.right_accel = right_accel_indicator;
main_window.UserData.indicators.left_device_settings = left_device_settings_indicator;
main_window.UserData.indicators.right_device_settings = right_device_settings_indicator;
main_window.UserData.indicators.delsys = delsys_indicator;
main_window.UserData.indicators.xsens = xsens_indicator;
main_window.UserData.indicators.fp = force_plate_indicator;
main_window.UserData.indicators.teensey = teensey_indicator;

end